### ISSUE TITLE
[BUG] vertices mesh crashes in parallel

### ISSUE THREAD

**Issue by jhdark** [RemDelaporteMathurin/FESTIM#497]
**Describe the bug**
When running a case in FESTIM with a MeshFromVertices class, an error is produced when running the script in parallel

**To Reproduce**
```python
import FESTIM as F
import numpy as np

my_model = F.Simulation(log_level=20)
vertices = np.linspace(0, 1, num=100)
my_model.mesh = F.MeshFromVertices(vertices=vertices)
mat = F.Material(
    id=1,
    D_0=1,
    E_D=0,
)
my_model.materials = F.Materials([mat])
my_model.T = F.Temperature(value=300)
my_model.boundary_conditions = [
    F.DirichletBC(surfaces=1, value=1e20, field=0),
    F.DirichletBC(surfaces=0, value=0, field=0),
]
my_model.settings = F.Settings(
    transient=False,
    absolute_tolerance=1e12,
    relative_tolerance=1e-08,
    traps_element_type="DG",
    maximum_iterations=50,
)
my_model.initialise()
my_model.run()
```
produces the error:

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    my_model.initialise()
  File "/usr/local/lib/python3.6/dist-packages/FESTIM/generic_simulation.py", line 244, in initialise
    self.T.create_functions(self.mesh)
  File "/usr/local/lib/python3.6/dist-packages/FESTIM/temperature/temperature.py", line 42, in create_functions
    self.T.assign(f.interpolate(self.expression, V))
  File "/usr/local/lib/python3.6/dist-packages/dolfin/fem/interpolation.py", line 71, in interpolate
    Pv.interpolate(v._cpp_object)
  File "/usr/local/lib/python3.6/dist-packages/dolfin/function/function.py", line 365, in interpolate
    self._cpp_object.interpolate(u)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to interpolate function into function space.
*** Reason:  Wrong size of vector.
*** Where:   This error was encountered inside FunctionSpace.cpp.
*** Process: 1
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  74d7efe1e84d65e9433fd96c50f1d278fa3e3f3f
*** -------------------------------------------------------------------------
```
**Expected behavior**

**Screenshots**

**Comment by RemDelaporteMathurin** [comment]
```python
import fenics as f
import numpy as np


vertices = sorted(np.linspace(0, 1, num=99))
nb_points = len(vertices)
nb_cells = nb_points - 1
editor = f.MeshEditor()
mesh = f.Mesh()
editor.open(mesh, "interval", 1, 1)  # top. and geom. dimension are both 1
editor.init_vertices(nb_points)  # number of vertices
editor.init_cells(nb_cells)  # number of cells
for i in range(0, nb_points):
    editor.add_vertex(i, np.array([vertices[i]]))
for j in range(0, nb_cells):
    editor.add_cell(j, np.array([j, j + 1]))
editor.close()

V = f.FunctionSpace(mesh, "P", 1)
u = f.interpolate(f.Constant(300), V)
```

This is a pure fenics MWE.

Fails with 

```
mpirun -np 2 python3 test.py
```

**Comment by KulaginVladimir** [comment]
@jhdark, @RemDelaporteMathurin 

Hi there! Has this bug been fixed? If not, please see this [issue](https://bitbucket.org/fenics-project/dolfin/issues/403/mesheditor-and-meshinit-not-initializing). As stated there, `fenics.MeshEditor` creates only local mesh. 

Suggested solution is to create mesh with `fenics.MeshEditor` on `rank==0` and distribute it with `fenics.MeshPartitioning.build_distributed_mesh()`:
```python
import fenics as f
import numpy as np
from mpi4py import MPI

rank = MPI.COMM_WORLD.Get_rank()
mesh = f.Mesh()

if rank==0:
    vertices = sorted(np.linspace(0, 1, num=11))
    nb_points = len(vertices)
    nb_cells = nb_points - 1
    editor = f.MeshEditor()
    editor.open(mesh, "interval", 1, 1)  # top. and geom. dimension are both 1
    editor.init_vertices(nb_points)  # number of vertices
    editor.init_cells(nb_cells)  # number of cells
    for i in range(0, nb_points):
        editor.add_vertex(i, np.array([vertices[i]]))
    for j in range(0, nb_cells):
        editor.add_cell(j, np.array([j, j + 1]))
    editor.close()
    f.info(mesh)

f.MeshPartitioning.build_distributed_mesh(mesh)
f.info(mesh)

V = f.FunctionSpace(mesh, "P", 1)
u = f.interpolate(f.Expression("x[0]", degree = 2), V)

print('Rank: {}, array: {}'.format(rank,[u.vector()[:]]))
``` 

Running with `mpirun -np 1` results in:
```
<Mesh of topological dimension 1 (intervals) with 11 vertices and 10 cells, ordered>
<Mesh of topological dimension 1 (intervals) with 11 vertices and 10 cells, ordered>
Rank: 0, array: [array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])]
``` 

Running with `mpirun -np 2` produces:
```
Process 0: <Mesh of topological dimension 1 (intervals) with 11 vertices and 10 cells, ordered>
Process 0: <Mesh of topological dimension 1 (intervals) with 6 vertices and 5 cells, ordered>
Process 1: <Mesh of topological dimension 1 (intervals) with 6 vertices and 5 cells, ordered>
Rank: 0, array: [array([0.4, 0.3, 0.2, 0.1, 0. ])]
Rank: 1, array: [array([1. , 0.9, 0.8, 0.7, 0.6, 0.5])]
``` 

Please, check if this is the case

**Comment by RemDelaporteMathurin** [comment]
Hi @KulaginVladimir no this issue hasn't been fixed unfortunately.

It looks like your fix is effective! Would you mind opening a PR?

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin 

> It looks like your fix is effective! Would you mind opening a PR?

Sure 

> Does it also work without the mpirun call?

Yes, this example works:

```
vvkulagin@tensor:/mnt/pool/6/vvkulagin/FESTIM/test$ python3 test.py 
<Mesh of topological dimension 1 (intervals) with 11 vertices and 10 cells, ordered>
<Mesh of topological dimension 1 (intervals) with 11 vertices and 10 cells, ordered>
Rank: 0, array: [array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])]
```
