### ISSUE TITLE
[BUG] temperature cannot be ufl.conditional

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [RemDelaporteMathurin/FESTIM#626]
**Describe the bug**
When trying to set the temperature as a `ufl.conditional` it raises a `TypeError`.

```
Traceback (most recent call last):
  File "/home/remidm/festim/mwe.py", line 48, in <module>
    my_model.initialise()
  File "/home/remidm/festim/festim/hydrogen_transport_problem.py", line 184, in initialise
    self.define_temperature()
  File "/home/remidm/festim/festim/hydrogen_transport_problem.py", line 216, in define_temperature
    self.temperature_fenics = F.as_fenics_constant(
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/remidm/festim/festim/helpers.py", line 22, in as_fenics_constant
    raise TypeError(
TypeError: Value must be a float, an int or a dolfinx.Constant, not <class 'ufl.conditional.Conditional'>
```

**To Reproduce**
Run:

```python
import festim as F
import numpy as np

L = 3e-04
vertices = np.linspace(0, L, num=1000)

my_mesh = F.Mesh1D(vertices)

my_model = F.HydrogenTransportProblem()
my_model.mesh = my_mesh

my_mat = F.Material(D_0=1.9e-7, E_D=0.2, name="my_mat")
my_subdomain = F.VolumeSubdomain1D(id=1, borders=[0, L], material=my_mat)
left_surface = F.SurfaceSubdomain1D(id=1, x=0)
right_surface = F.SurfaceSubdomain1D(id=2, x=L)
my_model.subdomains = [
    my_subdomain,
    left_surface,
    right_surface,
]

my_model.species = [F.Species("H")]


from ufl import conditional, lt

implantation_time = 100
implantation_temp = 300
temperature_ramp = 5  # K/s


def temp_function(t):
    ramping_temperature = implantation_temp + temperature_ramp * (t - implantation_time)
    return conditional(lt(t, implantation_time), implantation_temp, ramping_temperature)


my_model.temperature = temp_function

my_model.settings = F.Settings(
    atol=1e10,
    rtol=1e-10,
    max_iterations=30,
    final_time=200,
)

my_model.settings.stepsize = F.Stepsize(initial_value=1 / 20)

my_model.initialise()

```

**Comment by RemDelaporteMathurin** [comment]
same problem for using `ufl.conditional` as the value of a `DirichletBC`.

I think we just need to adapt the logic a bit

**Comment by RemDelaporteMathurin** [comment]
Other cases to consider:

- `value = lambda t: 1 + conditional(...)`
- `value = lambda t, x: x[0] + conditional(...)`
- `value = lambda x: conditional(x < 1, 0, 2)`

**Comment by RemDelaporteMathurin** [comment]
After more investigation, it appears this only happens when a function of `t` only is passed and ufl.conditional is used.

In this case, users should pass:

```python
lambda t: 100.0 if t < 1 else 0.0
```
Instead of 
```python
lambda t: conditional(lt(t, 1), 100.0, 0.0)
```
